steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/synapse-repo/synapse-api:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/synapse-repo/synapse-api:latest'